name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The warp version you want to build"
        required: true
      latest:
        description: "tag as latest"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_REPO }}
        tags: |
          type=raw,value=${{ github.event.inputs.version }}
          type=raw,value=latest,enable=${{ github.event.inputs.latest }}
        sep-tags: ','
        sep-labels: ','
    - name: Docker Build & Push Version
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        registry: docker.io
        image: ${{ secrets.DOCKERHUB_REPO }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        buildArgs: VERSION=${{ github.event.inputs.version }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}